name: CustomMT
version: '1.0'
main: nl.inferno.customMT.CustomMT
api-version: '1.19'
depend: [Vault]
author: Inferno
commands:
  politie:
    description: Only for Police
  gemeente:
    description: Gemeente Main Duty
  setspawn:
    description: Set the Spawn
  staff:
    description: Staff Mode (Only for Staff)
  build:
    description: Build Mode (Only for Staff)
    